[package]
name = "ethereum-address-generator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
secp256k1 = "0.20"
rand = "0.8"
sha3 = "0.10"
hex = "0.4"
